/*
|--------------------------------------------------------------------------
| CodeBuddy Execution Limits
|--------------------------------------------------------------------------
|
| Centralized execution limits for code running inside room containers.
|
| These limits are applied by the execution layer before/during execution.
|
| Architecture:
|
|   Room
|     │
|     ▼
|   Docker Container
|     │
|     ▼
|   Execution Manager
|     │
|     ├── Runtime Resolver
|     ├── Execution Limits  <── THIS FILE
|     └── Process Runner
|
|--------------------------------------------------------------------------
*/

/*
|--------------------------------------------------------------------------
| Supported Execution Modes
|--------------------------------------------------------------------------
*/

export type ExecutionMode =
    | "run"
    | "compile"
    | "test"
    | "build"
    | "terminal";

/*
|--------------------------------------------------------------------------
| Resource Limits
|--------------------------------------------------------------------------
*/

export interface ResourceLimits {
    /*
     * Maximum execution time for a single process.
     *
     * Example:
     * Python program gets 10 seconds.
     */
    timeoutMs: number;

    /*
     * Maximum amount of memory available to the process.
     */
    memoryBytes: number;

    /*
     * Maximum memory including swap.
     *
     * Use 0 when swap should not be allowed.
     */
    memorySwapBytes: number;

    /*
     * Maximum number of processes/threads.
     */
    pidsLimit: number;

    /*
     * Maximum CPU allocation.
     *
     * Docker NanoCPUs:
     *
     * 1 CPU = 1_000_000_000
     */
    nanoCpus: number;

    /*
     * Maximum output generated by stdout.
     */
    maxStdoutBytes: number;

    /*
     * Maximum output generated by stderr.
     */
    maxStderrBytes: number;

    /*
     * Maximum combined stdout + stderr.
     */
    maxOutputBytes: number;

    /*
     * Maximum source code size.
     */
    maxSourceBytes: number;

    /*
     * Maximum number of files involved in execution.
     */
    maxFiles: number;

    /*
     * Maximum file size that execution may generate.
     */
    maxGeneratedFileBytes: number;

    /*
     * Maximum total workspace growth caused by execution.
     */
    maxWorkspaceGrowthBytes: number;
}

/*
|--------------------------------------------------------------------------
| Default Limits
|--------------------------------------------------------------------------
|
| These values are intentionally conservative for an online IDE.
|
|--------------------------------------------------------------------------
*/

export const DEFAULT_EXECUTION_LIMITS:
    ResourceLimits = {
    /*
     * 10 seconds
     */
    timeoutMs:
        10_000,

    /*
     * 512 MB
     */
    memoryBytes:
        512 * 1024 * 1024,

    /*
     * Disable swap expansion.
     */
    memorySwapBytes:
        512 * 1024 * 1024,

    /*
     * Prevent fork bombs / excessive processes.
     */
    pidsLimit:
        64,

    /*
     * 1 CPU core.
     */
    nanoCpus:
        1_000_000_000,

    /*
     * 1 MB stdout.
     */
    maxStdoutBytes:
        1 * 1024 * 1024,

    /*
     * 1 MB stderr.
     */
    maxStderrBytes:
        1 * 1024 * 1024,

    /*
     * 2 MB combined output.
     */
    maxOutputBytes:
        2 * 1024 * 1024,

    /*
     * 10 MB source file.
     */
    maxSourceBytes:
        10 * 1024 * 1024,

    /*
     * Maximum number of files participating in execution.
     */
    maxFiles:
        500,

    /*
     * Maximum generated file size.
     */
    maxGeneratedFileBytes:
        50 * 1024 * 1024,

    /*
     * Maximum workspace growth caused by a process.
     */
    maxWorkspaceGrowthBytes:
        200 * 1024 * 1024,
};

/*
|--------------------------------------------------------------------------
| Language-Specific Execution Limits
|--------------------------------------------------------------------------
|
| Different languages can require different execution characteristics.
|
| These are limits, not runtime definitions.
|
|--------------------------------------------------------------------------
*/

export const LANGUAGE_EXECUTION_LIMITS:
    Record<
        string,
        Partial<ResourceLimits>
    > = {
    /*
     * Python
     */
    python: {
        timeoutMs:
            10_000,

        memoryBytes:
            512 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * JavaScript / Node.js
     */
    javascript: {
        timeoutMs:
            10_000,

        memoryBytes:
            512 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    node: {
        timeoutMs:
            10_000,

        memoryBytes:
            512 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * TypeScript
     */
    typescript: {
        timeoutMs:
            15_000,

        memoryBytes:
            768 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * Java
     */
    java: {
        timeoutMs:
            15_000,

        memoryBytes:
            768 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * C
     */
    c: {
        timeoutMs:
            10_000,

        memoryBytes:
            512 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * C++
     */
    cpp: {
        timeoutMs:
            10_000,

        memoryBytes:
            512 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * Go
     */
    go: {
        timeoutMs:
            10_000,

        memoryBytes:
            512 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * Rust
     *
     * Compilation can take longer.
     */
    rust: {
        timeoutMs:
            30_000,

        memoryBytes:
            1 * 1024 * 1024 * 1024,

        pidsLimit:
            128,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * PHP
     */
    php: {
        timeoutMs:
            10_000,

        memoryBytes:
            512 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * Ruby
     */
    ruby: {
        timeoutMs:
            10_000,

        memoryBytes:
            512 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * Kotlin
     */
    kotlin: {
        timeoutMs:
            20_000,

        memoryBytes:
            768 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },

    /*
     * Swift
     */
    swift: {
        timeoutMs:
            20_000,

        memoryBytes:
            768 * 1024 * 1024,

        pidsLimit:
            64,

        maxOutputBytes:
            2 * 1024 * 1024,
    },
};

/*
|--------------------------------------------------------------------------
| Execution Profile
|--------------------------------------------------------------------------
*/

export interface ExecutionProfile
    extends ResourceLimits {
    language: string;

    mode: ExecutionMode;
}

/*
|--------------------------------------------------------------------------
| Merge Limits
|--------------------------------------------------------------------------
*/

export function getExecutionLimits(
    language: string,
    overrides: Partial<ResourceLimits> = {}
): ResourceLimits {
    const normalizedLanguage =
        language
            .trim()
            .toLowerCase();

    const languageLimits =
        LANGUAGE_EXECUTION_LIMITS[
            normalizedLanguage
        ] ?? {};

    return {
        ...DEFAULT_EXECUTION_LIMITS,

        ...languageLimits,

        ...overrides,
    };
}

/*
|--------------------------------------------------------------------------
| Get Execution Profile
|--------------------------------------------------------------------------
*/

export function getExecutionProfile(
    language: string,
    mode: ExecutionMode = "run",
    overrides: Partial<ResourceLimits> = {}
): ExecutionProfile {
    return {
        language:
            language
                .trim()
                .toLowerCase(),

        mode,

        ...getExecutionLimits(
            language,
            overrides
        ),
    };
}

/*
|--------------------------------------------------------------------------
| Compilation Limits
|--------------------------------------------------------------------------
|
| Compilation should normally receive more time than execution.
|
|--------------------------------------------------------------------------
*/

export function getCompilationLimits(
    language: string
): ResourceLimits {
    const base =
        getExecutionLimits(
            language
        );

    return {
        ...base,

        timeoutMs:
            Math.max(
                base.timeoutMs,
                30_000
            ),

        maxOutputBytes:
            Math.max(
                base.maxOutputBytes,
                4 * 1024 * 1024
            ),
    };
}

/*
|--------------------------------------------------------------------------
| Build Limits
|--------------------------------------------------------------------------
*/

export function getBuildLimits(
    language: string
): ResourceLimits {
    const base =
        getExecutionLimits(
            language
        );

    return {
        ...base,

        timeoutMs:
            Math.max(
                base.timeoutMs,
                60_000
            ),

        maxOutputBytes:
            Math.max(
                base.maxOutputBytes,
                5 * 1024 * 1024
            ),
    };
}

/*
|--------------------------------------------------------------------------
| Terminal Limits
|--------------------------------------------------------------------------
|
| Terminal sessions are different from normal execution.
|
| A terminal can stay alive longer, but still has output
| and process limits.
|
|--------------------------------------------------------------------------
*/

export const TERMINAL_LIMITS:
    ResourceLimits = {
    ...DEFAULT_EXECUTION_LIMITS,

    timeoutMs:
        30 * 60 * 1000,

    maxOutputBytes:
        10 * 1024 * 1024,

    maxStdoutBytes:
        5 * 1024 * 1024,

    maxStderrBytes:
        5 * 1024 * 1024,

    pidsLimit:
        128,
};

/*
|--------------------------------------------------------------------------
| AI / ML Execution Limits
|--------------------------------------------------------------------------
|
| AI/ML programs can require more memory.
|
| These values are still intended for CPU-based execution.
|
| GPU execution should have a separate policy.
|
|--------------------------------------------------------------------------
*/

export const AI_ML_LIMITS:
    ResourceLimits = {
    ...DEFAULT_EXECUTION_LIMITS,

    timeoutMs:
        60_000,

    memoryBytes:
        2 * 1024 * 1024 * 1024,

    memorySwapBytes:
        2 * 1024 * 1024 * 1024,

    pidsLimit:
        128,

    nanoCpus:
        2_000_000_000,

    maxOutputBytes:
        5 * 1024 * 1024,

    maxWorkspaceGrowthBytes:
        500 * 1024 * 1024,
};

/*
|--------------------------------------------------------------------------
| Full-Stack Development Limits
|--------------------------------------------------------------------------
|
| Full-stack projects may run multiple processes:
|
|   Node
|   Python
|   Java
|   database client
|   frontend dev server
|
| These limits are therefore higher than single-program execution.
|
|--------------------------------------------------------------------------
*/

export const FULL_STACK_LIMITS:
    ResourceLimits = {
    ...DEFAULT_EXECUTION_LIMITS,

    timeoutMs:
        5 * 60 * 1000,

    memoryBytes:
        1 * 1024 * 1024 * 1024,

    memorySwapBytes:
        1 * 1024 * 1024 * 1024,

    pidsLimit:
        256,

    nanoCpus:
        2_000_000_000,

    maxOutputBytes:
        10 * 1024 * 1024,

    maxWorkspaceGrowthBytes:
        500 * 1024 * 1024,
};

/*
|--------------------------------------------------------------------------
| Validation Errors
|--------------------------------------------------------------------------
*/

export class ExecutionLimitError
    extends Error {
    constructor(
        message: string
    ) {
        super(message);

        this.name =
            "ExecutionLimitError";
    }
}

/*
|--------------------------------------------------------------------------
| Validate Source Size
|--------------------------------------------------------------------------
*/

export function validateSourceSize(
    sizeBytes: number,
    limits: ResourceLimits
): void {
    if (
        !Number.isFinite(
            sizeBytes
        ) ||
        sizeBytes < 0
    ) {
        throw new ExecutionLimitError(
            "Invalid source size"
        );
    }

    if (
        sizeBytes >
        limits.maxSourceBytes
    ) {
        throw new ExecutionLimitError(
            `Source code exceeds maximum allowed size of ${formatBytes(
                limits.maxSourceBytes
            )}`
        );
    }
}

/*
|--------------------------------------------------------------------------
| Validate File Count
|--------------------------------------------------------------------------
*/

export function validateFileCount(
    fileCount: number,
    limits: ResourceLimits
): void {
    if (
        !Number.isInteger(
            fileCount
        ) ||
        fileCount < 0
    ) {
        throw new ExecutionLimitError(
            "Invalid file count"
        );
    }

    if (
        fileCount >
        limits.maxFiles
    ) {
        throw new ExecutionLimitError(
            `Execution contains too many files. Maximum allowed: ${limits.maxFiles}`
        );
    }
}

/*
|--------------------------------------------------------------------------
| Validate Generated File Size
|--------------------------------------------------------------------------
*/

export function validateGeneratedFileSize(
    sizeBytes: number,
    limits: ResourceLimits
): void {
    if (
        !Number.isFinite(
            sizeBytes
        ) ||
        sizeBytes < 0
    ) {
        throw new ExecutionLimitError(
            "Invalid generated file size"
        );
    }

    if (
        sizeBytes >
        limits.maxGeneratedFileBytes
    ) {
        throw new ExecutionLimitError(
            `Generated file exceeds maximum allowed size of ${formatBytes(
                limits.maxGeneratedFileBytes
            )}`
        );
    }
}

/*
|--------------------------------------------------------------------------
| Validate Timeout
|--------------------------------------------------------------------------
*/

export function validateTimeout(
    timeoutMs: number,
    limits: ResourceLimits
): void {
    if (
        !Number.isFinite(
            timeoutMs
        ) ||
        timeoutMs <= 0
    ) {
        throw new ExecutionLimitError(
            "Invalid execution timeout"
        );
    }

    if (
        timeoutMs >
        limits.timeoutMs
    ) {
        throw new ExecutionLimitError(
            `Requested timeout exceeds maximum allowed timeout of ${limits.timeoutMs}ms`
        );
    }
}

/*
|--------------------------------------------------------------------------
| Validate Output Size
|--------------------------------------------------------------------------
*/

export function validateOutputSize(
    sizeBytes: number,
    limits: ResourceLimits
): void {
    if (
        !Number.isFinite(
            sizeBytes
        ) ||
        sizeBytes < 0
    ) {
        throw new ExecutionLimitError(
            "Invalid output size"
        );
    }

    if (
        sizeBytes >
        limits.maxOutputBytes
    ) {
        throw new ExecutionLimitError(
            `Process output exceeded maximum allowed size of ${formatBytes(
                limits.maxOutputBytes
            )}`
        );
    }
}

/*
|--------------------------------------------------------------------------
| Validate Memory
|--------------------------------------------------------------------------
*/

export function validateMemory(
    memoryBytes: number,
    limits: ResourceLimits
): void {
    if (
        !Number.isFinite(
            memoryBytes
        ) ||
        memoryBytes <= 0
    ) {
        throw new ExecutionLimitError(
            "Invalid memory limit"
        );
    }

    if (
        memoryBytes >
        limits.memoryBytes
    ) {
        throw new ExecutionLimitError(
            `Requested memory exceeds maximum allowed memory of ${formatBytes(
                limits.memoryBytes
            )}`
        );
    }
}

/*
|--------------------------------------------------------------------------
| Validate Resource Limits
|--------------------------------------------------------------------------
*/

export function validateLimits(
    limits: ResourceLimits
): void {
    if (
        limits.timeoutMs <= 0
    ) {
        throw new ExecutionLimitError(
            "timeoutMs must be greater than zero"
        );
    }

    if (
        limits.memoryBytes <= 0
    ) {
        throw new ExecutionLimitError(
            "memoryBytes must be greater than zero"
        );
    }

    if (
        limits.memorySwapBytes <
        limits.memoryBytes
    ) {
        throw new ExecutionLimitError(
            "memorySwapBytes cannot be lower than memoryBytes"
        );
    }

    if (
        limits.pidsLimit <= 0
    ) {
        throw new ExecutionLimitError(
            "pidsLimit must be greater than zero"
        );
    }

    if (
        limits.nanoCpus <= 0
    ) {
        throw new ExecutionLimitError(
            "nanoCpus must be greater than zero"
        );
    }

    if (
        limits.maxStdoutBytes <= 0
    ) {
        throw new ExecutionLimitError(
            "maxStdoutBytes must be greater than zero"
        );
    }

    if (
        limits.maxStderrBytes <= 0
    ) {
        throw new ExecutionLimitError(
            "maxStderrBytes must be greater than zero"
        );
    }

    if (
        limits.maxOutputBytes <= 0
    ) {
        throw new ExecutionLimitError(
            "maxOutputBytes must be greater than zero"
        );
    }

    if (
        limits.maxSourceBytes <= 0
    ) {
        throw new ExecutionLimitError(
            "maxSourceBytes must be greater than zero"
        );
    }

    if (
        limits.maxFiles <= 0
    ) {
        throw new ExecutionLimitError(
            "maxFiles must be greater than zero"
        );
    }

    if (
        limits.maxGeneratedFileBytes <=
        0
    ) {
        throw new ExecutionLimitError(
            "maxGeneratedFileBytes must be greater than zero"
        );
    }

    if (
        limits.maxWorkspaceGrowthBytes <=
        0
    ) {
        throw new ExecutionLimitError(
            "maxWorkspaceGrowthBytes must be greater than zero"
        );
    }
}

/*
|--------------------------------------------------------------------------
| Clamp Requested Limits
|--------------------------------------------------------------------------
|
| User/client input should NEVER be allowed to increase the
| server-defined maximum.
|
|--------------------------------------------------------------------------
*/

export function clampLimits(
    requested: Partial<ResourceLimits>,
    maximum: ResourceLimits =
        DEFAULT_EXECUTION_LIMITS
): ResourceLimits {
    return {
        timeoutMs:
            Math.min(
                requested.timeoutMs ??
                    maximum.timeoutMs,
                maximum.timeoutMs
            ),

        memoryBytes:
            Math.min(
                requested.memoryBytes ??
                    maximum.memoryBytes,
                maximum.memoryBytes
            ),

        memorySwapBytes:
            Math.min(
                requested.memorySwapBytes ??
                    maximum.memorySwapBytes,
                maximum.memorySwapBytes
            ),

        pidsLimit:
            Math.min(
                requested.pidsLimit ??
                    maximum.pidsLimit,
                maximum.pidsLimit
            ),

        nanoCpus:
            Math.min(
                requested.nanoCpus ??
                    maximum.nanoCpus,
                maximum.nanoCpus
            ),

        maxStdoutBytes:
            Math.min(
                requested.maxStdoutBytes ??
                    maximum.maxStdoutBytes,
                maximum.maxStdoutBytes
            ),

        maxStderrBytes:
            Math.min(
                requested.maxStderrBytes ??
                    maximum.maxStderrBytes,
                maximum.maxStderrBytes
            ),

        maxOutputBytes:
            Math.min(
                requested.maxOutputBytes ??
                    maximum.maxOutputBytes,
                maximum.maxOutputBytes
            ),

        maxSourceBytes:
            Math.min(
                requested.maxSourceBytes ??
                    maximum.maxSourceBytes,
                maximum.maxSourceBytes
            ),

        maxFiles:
            Math.min(
                requested.maxFiles ??
                    maximum.maxFiles,
                maximum.maxFiles
            ),

        maxGeneratedFileBytes:
            Math.min(
                requested.maxGeneratedFileBytes ??
                    maximum.maxGeneratedFileBytes,
                maximum.maxGeneratedFileBytes
            ),

        maxWorkspaceGrowthBytes:
            Math.min(
                requested.maxWorkspaceGrowthBytes ??
                    maximum.maxWorkspaceGrowthBytes,
                maximum.maxWorkspaceGrowthBytes
            ),
    };
}

/*
|--------------------------------------------------------------------------
| Calculate CPU Cores
|--------------------------------------------------------------------------
*/

export function nanoCpusToCores(
    nanoCpus: number
): number {
    return (
        nanoCpus /
        1_000_000_000
    );
}

/*
|--------------------------------------------------------------------------
| Calculate Bytes
|--------------------------------------------------------------------------
*/

export function formatBytes(
    bytes: number
): string {
    if (
        bytes === 0
    ) {
        return "0 B";
    }

    const units = [
        "B",
        "KB",
        "MB",
        "GB",
        "TB",
    ];

    const index =
        Math.floor(
            Math.log(bytes) /
                Math.log(1024)
        );

    const safeIndex =
        Math.min(
            index,
            units.length - 1
        );

    const value =
        bytes /
        Math.pow(
            1024,
            safeIndex
        );

    return `${value.toFixed(
        value >= 10 ? 0 : 2
    )} ${units[safeIndex]}`;
}

/*
|--------------------------------------------------------------------------
| Environment Overrides
|--------------------------------------------------------------------------
|
| Production deployments can change the global limits without
| modifying source code.
|
| Example .env:
|
| EXECUTION_TIMEOUT_MS=10000
| EXECUTION_MEMORY_MB=512
| EXECUTION_PIDS_LIMIT=64
|
|--------------------------------------------------------------------------
*/

function getEnvNumber(
    name: string,
    fallback: number
): number {
    const value =
        process.env[name];

    if (
        value === undefined ||
        value.trim() === ""
    ) {
        return fallback;
    }

    const parsed =
        Number(value);

    if (
        !Number.isFinite(
            parsed
        ) ||
        parsed <= 0
    ) {
        return fallback;
    }

    return parsed;
}

/*
|--------------------------------------------------------------------------
| Production Limits
|--------------------------------------------------------------------------
*/

export const PRODUCTION_EXECUTION_LIMITS:
    ResourceLimits = {
    ...DEFAULT_EXECUTION_LIMITS,

    timeoutMs:
        getEnvNumber(
            "EXECUTION_TIMEOUT_MS",
            DEFAULT_EXECUTION_LIMITS.timeoutMs
        ),

    memoryBytes:
        getEnvNumber(
            "EXECUTION_MEMORY_MB",
            DEFAULT_EXECUTION_LIMITS.memoryBytes /
                (1024 * 1024)
        ) *
        1024 *
        1024,

    pidsLimit:
        getEnvNumber(
            "EXECUTION_PIDS_LIMIT",
            DEFAULT_EXECUTION_LIMITS.pidsLimit
        ),

    maxOutputBytes:
        getEnvNumber(
            "EXECUTION_MAX_OUTPUT_MB",
            DEFAULT_EXECUTION_LIMITS.maxOutputBytes /
                (1024 * 1024)
        ) *
        1024 *
        1024,
};

/*
|--------------------------------------------------------------------------
| Final Validation
|--------------------------------------------------------------------------
*/

validateLimits(
    DEFAULT_EXECUTION_LIMITS
);

validateLimits(
    TERMINAL_LIMITS
);

validateLimits(
    AI_ML_LIMITS
);

validateLimits(
    FULL_STACK_LIMITS
);